Repository nori-dongsan/nori-Server, pull requests merged in 2022-07, with the labels that each got.

#4 setting: entity 생성
  .gitignore
  jest.config.ts
  package.json
  src/app.ts
  src/config/ioc.ts
  src/config/provideSingleton.ts
  src/controllers/AuthController.ts
  src/controllers/TestController.ts
  src/database.ts
  src/dtos/UserDto.ts
  src/entities/Board.ts
  src/entities/BoardComment.ts
  src/entities/BoardImage.ts
  src/entities/LikeToy.ts
  src/entities/Toy.ts
  src/entities/ToyCategory.ts
  src/entities/ToySite.ts
  src/entities/User.ts
  src/env.ts
  src/interfaces/common/PostBaseResponseDto.ts
  src/interfaces/common/SuccessResponse.ts
  src/interfaces/test/UserCreateDto.ts
  src/modules/responseMessage.ts
  src/modules/statusCode.ts
  src/modules/util.ts
  src/repositories/TestRepository.ts
  src/repositories/UserRepository.ts
  src/routes/routes.ts
  src/server.ts
  src/services/userService.ts
  src/swagger.json
  src/utils/ErrorType.ts
  src/utils/Logger.ts
  src/utils/ResponseMessage.ts
  src/utils/RoutingConfig.ts
  src/utils/Swagger.ts
  src/utils/success.ts
  test/e2e/utils/testApp.ts
  test/unit/services/UserService.test.ts
  test/utils/CreateMemoryDatabase.ts
  test/utils/JestSetup.ts
  test/utils/seeds/UserTestSeed.ts
  tsconfig.json
  tsoa.json
  yarn.lock
Labels: 👾 Crayon

#8 Feat/#6
  package.json
  src/constants/ReturnErrorType.ts
  src/controllers/AuthController.ts
  src/dtos/UserDto.ts
  src/entities/User.ts
  src/middlewares/AuthMiddleware.ts
  src/modules/responseMessage.ts
  src/services/AuthService.ts
  src/services/userService.ts
  test/unit/services/UserService.test.ts
  yarn.lock
Labels: 👾 Crayon, 🐬 Feat, user

#16 [GET] 홈 api
  src/controllers/HomeController.ts
  src/dtos/HomeDto.ts
  src/dtos/ToyDto.ts
  src/entities/LikeToy.ts
  src/entities/Toy.ts
  src/entities/ToyCategory.ts
  src/entities/ToySite.ts
  src/env.ts
  src/modules/responseMessage.ts
  src/repositories/HomeRepository.ts
  src/services/homeService.ts
  test/unit/services/HomeService.test.ts
  test/utils/seeds/FriendTestSeed.ts
Labels: 🦦 Danna

#34 Update: 회원가입 닉네임 중복 로직 분리
  src/controllers/AuthController.ts
  src/modules/responseMessage.ts
Labels: 👾 Crayon, 🔧 Refactor, user

#33 [GET] collection api
  src/controllers/BoardController.ts
  src/controllers/CollectionController.ts
  src/dtos/CollectionDto.ts
  src/entities/ToyCollection.ts
  src/modules/responseMessage.ts
  src/modules/s3.ts
  src/repositories/CollectionRepository.ts
  src/services/CollectionService.ts
  src/services/homeService.ts
  test/unit/services/CollectionService.test.ts
  test/unit/services/HomeService.test.ts
  test/utils/seeds/FriendTestSeed.ts
Labels: 🦦 Danna
